# See also: https://github.com/sorah/config/blob/master/bin/sorah-debuild
FROM debian:stretch

# just to invalidate cache
ENV NKMIBUILDREV=1

RUN mkdir -p /build \
  && apt-get update \
  && apt-get install -y debhelper dh-make devscripts gnupg2 vim equivs
RUN mkdir -p -m700 /root/.gnupg

ADD control /control
RUN mk-build-deps -i --t 'apt-get -y -o Debug::pkgProblemResolver=yes --no-install-recommends' /control
RUN apt-get install -y tzdata
