FROM debian:bullseye

# just to invalidate cache
ARG BUILDDATE=99999999

ENV DEBIAN_FRONTEND=noninteractive
RUN cat > /etc/apt/sources.list <<'EOF'
deb http://deb.debian.org/debian/ bookworm main contrib non-free-firmware non-free
deb-src http://deb.debian.org/debian/ bookworm main contrib non-free-firmware non-free

deb https://deb.debian.org/debian-security bookworm-security main contrib non-free-firmware non-free
deb-src https://deb.debian.org/debian-security bookworm-security main contrib non-free-firmware non-free
EOF
RUN mkdir -p /build \
  && apt-get update \
  && apt-get install -y debhelper dh-make devscripts gnupg2 vim equivs
RUN mkdir -p -m700 /root/.gnupg

ADD control /control
RUN mk-build-deps -i --t 'apt-get -y -o Debug::pkgProblemResolver=yes --no-install-recommends' /control
RUN apt-get install -y tzdata
