exclude :test_pause, 'failure against ruby2.7, needs further investigation'
exclude :test_pause_does_not_hang_on_full_units, 'failure against ruby2.7, needs further investigation'
exclude :test_pause_wait_false, 'failure against ruby2.7, needs further investigation'
exclude :test_pause_waits_until_compaction, 'failure against ruby2.7, needs further investigation'
exclude :test_resume, 'failure against ruby2.7, needs further investigation'
