on: [ push, pull_request ]

jobs:
  test:
    name: >-
      Test (${{ matrix.ruby-version }} / ${{ matrix.os }} / TEST_SYMLINK: ${{ matrix.TEST_SYMLINK }})
    strategy:
      fail-fast: false
      matrix:
        ruby-version: [ '3.0', 2.7, 2.6, 2.5, head ]
        os: [ ubuntu-latest, macos-latest ]
        TEST_SYMLINK: [ yes, no ]
    runs-on: ${{ matrix.os }}
    env:
      TEST_SYMLINK: ${{ matrix.TEST_SYMLINK }}
    continue-on-error: ${{ matrix.ruby-version == 'head' }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true
      - name: Run before_script
        run: |
          bundle exec rake before_script
      - name: Run the test suite
        run: |
          bundle exec rake
      - name: Run after_script
        run: |
          bundle exec rake after_script
